### ISSUE TITLE
GlobalAnalysis of different seq_database

### ISSUE THREAD

**Issue by poppop-dot** [alexarnimueller/modlAMP#16]
Hello @alexarnimueller：
I used the GlobalAnalysis method you provided to compare different sequence libraries:

Traceback (most recent call last):
  File "d:/reoccur/amp-gan/ampgan/evaluation/analyze_seq.py", line 44, in <module>
    analysis.plot_summary()
  File "E:\anaconda3\envs\ampgan_test\lib\site-packages\modlamp\analysis.py", line 304, in plot_summary
    color=colors[:num])
  File "E:\anaconda3\envs\ampgan_test\lib\site-packages\matplotlib\__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "E:\anaconda3\envs\ampgan_test\lib\site-packages\matplotlib\axes\_axes.py", line 6597, in hist
    raise ValueError(f"The 'color' keyword argument must have one "
ValueError: The 'color' keyword argument must have one color per dataset, but 2000 datasets and 3 colors were provided

The 2 D array shape of my input is (3,5000)。

**Comment by alexarnimueller** [comment]
It looks like your data frame is organized with one dataset per row. Can you try to transpose it to one dataset per column?
e.g. `df.T`

**Comment by poppop-dot** [comment]
In my attempt, only the (3,3) arrays can run, nothing else
